# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Déploiement en recette

on:
  push:
    branches: [ recette ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: yarn
    - name: Override .env
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_STRATEGYAUTH: "local"
        envkey_REACT_APP_VERSION: "1.2"
        envkey_REACT_APP_WEBMAIL_URL: "http://webmail.conseiller-numerique.fr"
        envkey_REACT_APP_MATTERMOST_URL: "https://discussion.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_API: ${{ secrets.REACT_APP_API_RECETTE }}
        envkey_REACT_APP_PIX_URL: "https://pix.fr/abc-pix-cnfs/"
        envkey_REACT_APP_LABASE_URL: "https://labase.anct.gouv.fr/base/3"
        envkey_REACT_APP_AIDE_URL: "https://aide.conseiller-numerique.gouv.fr/fr"
        envkey_REACT_APP_CARTOGRAPHIE_URL: "https://cartographie.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_RDV_AIDE_NUMERIQUE_URL: "https://www.rdv-aide-numerique.fr/agents/sign_in"
        envkey_REACT_APP_BLOG_URL: "https://media.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_NOMBRE_LIEU_SECONDAIRE: 15
        envkey_REACT_APP_SENTRY_ENABLED: "true"
        envkey_REACT_APP_SENTRY_ENVIRONMENT: "recette"
        envkey_REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_COOP_DSN }}
        envkey_REACT_APP_SENTRY_TRACE_RATE: "0.01"
        file_name: .env
    - name: Build application
      run: yarn run build
    - name: copy .htaccess
      uses: canastro/copy-file-action@master
      with:
        source: ".htaccess"
        target: "build/.htaccess"
    - name: Deploy on clever cloud
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: ${{ secrets.CLEVER_CLOUD_GIT_PORTAIL_CONSEILLER_RECETTE }}
        BRANCH: master
        FOLDER: build
        SSH_PRIVATE_KEY: ${{ secrets.CLEVER_CLOUD_DEPLOY_PRIVATE_KEY }}
        KNOWN_HOSTS_FILE: resources/known_hosts
