# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Déploiement en recette

on:
  push:
    branches: [ recette ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: yarn
    - name: Override .env
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_STRATEGYAUTH: "local"
        envkey_REACT_APP_VERSION: "1.2"
        envkey_REACT_APP_WEBMAIL_URL: "http://webmail.conseiller-numerique.fr"
        envkey_REACT_APP_MATTERMOST_URL: "https://discussion.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_API: ${{ secrets.REACT_APP_API_RECETTE }}
        envkey_REACT_APP_PIX_URL: "https://pix.fr/abc-pix-cnfs/"
        envkey_REACT_APP_PIX_CONNEXION_URL: "https://app.pix.fr/connexion"
        envkey_REACT_APP_PIX_CAMPAGNE_URL: ${{ secrets.REACT_APP_PIX_CAMPAGNE_URL }}
        envkey_REACT_APP_LABASE_URL: "https://labase.anct.gouv.fr/base/3"
        envkey_REACT_APP_AIDE_URL: "https://aide.conseiller-numerique.gouv.fr/fr"
        envkey_REACT_APP_CARTOGRAPHIE_URL: "https://beta.www.conseiller-numerique.gouv.fr/carte"
        envkey_REACT_APP_RDV_AIDE_NUMERIQUE_URL: "https://www.rdv-aide-numerique.fr/agents/sign_in"
        envkey_REACT_APP_BLOG_URL: "https://media.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_ESPACE_COOP_URL: "https://beta.coop.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_TABLEAU_DE_PILOTAGE_URL: "https://beta.pilotage.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_CRISP_URL: "https://go.crisp.chat/chat/embed/?website_id"
        envkey_REACT_APP_CRISP_ID: "ea669e13-e40f-40c8-be23-e43565c0e62c"
        envkey_REACT_APP_NOMBRE_LIEU_SECONDAIRE: 15
        envkey_REACT_APP_INIT_COORDONNEES: 1.849121,46.624100
        envkey_REACT_APP_CV_FILE_MAX_SIZE: 10485760
        envkey_REACT_APP_SENTRY_ENABLED: "true"
        envkey_REACT_APP_SENTRY_ENVIRONMENT: "recette"
        envkey_REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_COOP_DSN }}
        envkey_REACT_APP_SENTRY_TRACE_RATE: "0.01"
        file_name: .env
    - name: Build application
      run: yarn run build
    - name: copy .htaccess
      uses: canastro/copy-file-action@master
      with:
        source: ".htaccess"
        target: "build/.htaccess"
    - name: Deploy on clever cloud
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: ${{ secrets.CLEVER_CLOUD_GIT_PORTAIL_CONSEILLER_RECETTE }}
        BRANCH: master
        FOLDER: build
        SSH_PRIVATE_KEY: ${{ secrets.CLEVER_CLOUD_DEPLOY_PRIVATE_KEY }}
        KNOWN_HOSTS_FILE: resources/known_hosts
    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BETA_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_BETA_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_COOP_PROJECT }}
        SENTRY_URL: ${{ secrets.SENTRY_BETA_URL }}
      with:
        environment: recette
        ignore_missing: true
        ignore_empty: true
